"""empty message

Revision ID: 4005c2f31091
Revises: 42d2b25a931c
Create Date: 2017-09-18 20:14:30.777000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4005c2f31091'
down_revision = '42d2b25a931c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('email', sa.String(length=60), nullable=True))
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_column('employees', 'email')
    # ### end Alembic commands ###
