"""empty message

Revision ID: 42d2b25a931c
Revises: 5286455174e5
Create Date: 2017-09-18 17:11:10.070000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42d2b25a931c'
down_revision = '5286455174e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('age', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_customers_age'), 'customers', ['age'], unique=False)
    op.drop_index('ix_customers_phone_no', table_name='customers')
    op.create_index(op.f('ix_customers_phone_no'), 'customers', ['phone_no'], unique=True)
    op.drop_index('ix_customers_email', table_name='customers')
    op.drop_column('customers', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('email', mysql.VARCHAR(length=60), nullable=True))
    op.create_index('ix_customers_email', 'customers', ['email'], unique=True)
    op.drop_index(op.f('ix_customers_phone_no'), table_name='customers')
    op.create_index('ix_customers_phone_no', 'customers', ['phone_no'], unique=False)
    op.drop_index(op.f('ix_customers_age'), table_name='customers')
    op.drop_column('customers', 'age')
    # ### end Alembic commands ###
