"""empty message

Revision ID: 4ab84cafd52b
Revises: f547e4cd9ddd
Create Date: 2017-10-27 10:01:29.799000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab84cafd52b'
down_revision = 'f547e4cd9ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('removed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_removed_position'), 'removed', ['position'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_removed_position'), table_name='removed')
    op.drop_table('removed')
    # ### end Alembic commands ###
