"""empty message

Revision ID: 5fd78f4ef831
Revises: c8b7645f1c41
Create Date: 2017-10-17 12:53:59.580000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd78f4ef831'
down_revision = 'c8b7645f1c41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customerstore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('phone_no', sa.String(length=16), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('t_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customerstore_age'), 'customerstore', ['age'], unique=False)
    op.create_index(op.f('ix_customerstore_name'), 'customerstore', ['name'], unique=False)
    op.create_index(op.f('ix_customerstore_phone_no'), 'customerstore', ['phone_no'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customerstore_phone_no'), table_name='customerstore')
    op.drop_index(op.f('ix_customerstore_name'), table_name='customerstore')
    op.drop_index(op.f('ix_customerstore_age'), table_name='customerstore')
    op.drop_table('customerstore')
    # ### end Alembic commands ###
