"""empty message

Revision ID: c8b7645f1c41
Revises: 4005c2f31091
Create Date: 2017-09-20 13:06:04.086000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8b7645f1c41'
down_revision = '4005c2f31091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currentid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currentid_current'), 'currentid', ['current'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currentid_current'), table_name='currentid')
    op.drop_table('currentid')
    # ### end Alembic commands ###
