"""empty message

Revision ID: f547e4cd9ddd
Revises: 5fd78f4ef831
Create Date: 2017-10-17 13:44:36.954000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f547e4cd9ddd'
down_revision = '5fd78f4ef831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customerstore', 'is_done')
    op.drop_column('customerstore', 'is_current')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customerstore', sa.Column('is_current', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('customerstore', sa.Column('is_done', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
